[package]
name = "espanso-manager"
version = "0.1.0"
description = "Native Espanso snippet manager"
authors = ["orioninsist"]
edition = "2021"

[lib]
name = "espanso_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tauri = { version = "2", features = [] }
thiserror = "2"
